# Generated by Django 3.0.4 on 2020-05-20 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('atracoes', '0002_atracao_foto'),
        ('ponto_turistico', '0008_pontoturistico_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='atracoes',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atracoes.Atracao'),
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comentarios.Comentario'),
        ),
    ]
