# Generated by Django 3.0.4 on 2020-06-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('avaliacoes', '0001_initial'),
        ('ponto_turistico', '0010_auto_20200627_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, to='avaliacoes.Avaliacao'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(blank=True, to='comentarios.Comentario'),
        ),
    ]
